### PR TITLE
Return values from #run

### PR DESCRIPTION
**Pull request by appleton**
This would be handy so we can get a handle on the actual server instance returned from `runServer`

### CODE REVIEW

**Comment by jclem** [comment]
@appleton Looks good, you have a `describe.only` still in here, though. Feel free to fix and force push.

**Comment by appleton** [comment]
Gah! Thanks, I've removed it.

**Comment by jclem** [comment]
@appleton Merged this into `development` manually, using a new branching model. Will update here when I release.

**Comment by jclem** [comment]
@appleton Released in [v1.3.0](https://github.com/jclem/teamster/releases/tag/v1.3.0). Thanks!

**Pull request closed without merging**
